export const failureListings = ["./ba dun tss.mp3"
,"./bleh.mp3" 
,"./bruh.mp3" 
,"./buurrp.mp3" 
,"./crickets.mp3" 
,"./crowd laughing.mp3" 
,"./distortion.mp3" 
,"./explosion.mp3" 
,"./fart.mp3" 
,"./fatality.mp3" 
,"./goat scream.mp3" 
,"./hahahaha lol.mp3" 
,"./hey what happened.mp3" 
,"./laughing.mp3" 
,"./lol.mp3" 
,"./metal gear alert.mp3" 
,"./mission failed, we'll get 'em next time.mp3"
,"./no god please no.mp3 ./no (office).mp3"
,"./oh my god.mp3"
,"./Oof.mp3"
,"./pfft.mp3"
,"./record scratch.mp3"
,"./say what.mp3"
,"./sorry bro.mp3"
,"./splat.mp3"
,"./wet fart.mp3"
,"./wilhelm scream.mp3"
,"./windows error.mp3"
,"./you serious.mp3"
]