export const successListings = ["./anime woah.mp3" 
,"./ba dun dun.mp3" 
,"./daaamn.mp3" 
,"./do it.mp3" 
,"./drum roll.mp3" 
,"./ez - easy.mp3" 
,"./got em haha.mp3" 
,"./got em.mp3" 
,"./heheh boi.mp3" 
,"./hello there.mp3" 
,"./heyy, that's pretty good.mp3" 
,"./kazoo.mp3" 
,"./legitness.mp3" 
,"./look at this dude.mp3" 
,"./noice.mp3" 
,"./oh my god wow.mp3" 
,"./rubber duck.mp3" 
,"./shots fired.mp3" 
,"./taco bell.mp3" 
,"./ta-daaa.mp3" 
,"./toasty.mp3" 
,"./weeeee.mp3" 
,"./we'll be right back.mp3 ./wow.mp3"]
